language: erlang

sudo: true

env:
  - ARCH=arm

script:
  - "bash -ex .travis-ci.sh"
  - "cat /etc/os-release"
# script:
#   - cd test
#   - sudo ansible-playbook -i inventory -e "provision_docker_privileged=true" main.yaml --syntax-check
#   - sudo ansible-playbook -i inventory -e "provision_docker_privileged=true" main.yaml
#   - >
#     sudo ansible-playbook -i inventory -e "provision_docker_privileged=true" main.yaml
#     | grep -q 'changed=0.*failed=0'
#     && (echo 'Idempotence test: pass' && exit 0)
#     || (echo 'Idempotence test: fail' && exit 1)
