---
- name: Ensure apt cache is up to date
  apt:
    update_cache: yes

- name: Cloning python-openzwave
  git:
    repo: https://github.com/OpenZWave/python-openzwave.git
    dest: "{{ working_directory }}"
    update: no

- name: Install dependency
  pip:
    name: Cython
    virtualenv: "{{ virtualenv_path }}"

- name: Check if python-openzwave is already installed
  command: "{{ virtualenv_path }}/bin/pip list"
  register: packages
  changed_when: False

- name: Build python-openzwave
  shell: "{{ item }}"
  args:
    chdir: "{{ working_directory }}"
  when: "'openzwave' not in packages.stdout"
  with_items:
    - "make PYTHON_EXEC={{ virtualenv_path }}/bin/python common-deps"
    - "make PYTHON_EXEC={{ virtualenv_path }}/bin/python pip-deps"
    - "make PYTHON_EXEC={{ virtualenv_path }}/bin/python install"


# TODO: Add instructions on how to run and why and turn off home assistant

- name: Download dependencies for control panel
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - libgnutls28
    - libgnutlsxx28
    - libgnutls-dev

- name: Download libmicrohttpd
  unarchive:
    src: ftp://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.19.tar.gz
    dest: "{{ working_directory }}/openzwave/"
    copy: no

- name: Clone open-zwave-control-panel repository
  git:
    repo: https://github.com/OpenZwave/open-zwave-control-panel/ open-zwave-control-panel
    dest: "{{ working_directory }}/openzwave/"
    update: no


# Modify makefile

# Build

# Add to path
